#!/bin/bash
# Copyright (c) 2018-2023 The PirateCash Developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

mkdir -p dist
cp -r PirateCash-Qt.app dist/
$STRIP dist/PirateCash-Qt.app/Contents/MacOS/PirateCash-Qt
cat << EOF > dist/PirateCash-Qt.app/Contents/Resources/qt.conf
[Paths]
Translations=Resources
Plugins=PlugIns
EOF
mkdir -p dist/.background
sed 's/PACKAGE_NAME/PirateCash/' < "contrib/dmgbuild/background.svg" | rsvg-convert -f png -d 36 -p 36 | convert - dpi36.background.tiff
sed 's/PACKAGE_NAME/PirateCash/' < "contrib/dmgbuild/background.svg" | rsvg-convert -f png -d 72 -p 72 | convert - dpi72.background.tiff
tiffcp -c none dpi36.background.tiff dpi72.background.tiff dist/.background/background.tiff
cp depends/x86_64-apple-darwin*/translations/{qt_da.qm,qt_de.qm,qt_es.qm,qt_hu.qm,qt_ru.qm,qt_uk.qm,qt_zh_CN.qm,qt_zh_TW.qm} dist/PirateCash-Qt.app/Contents/Resources
cd dist
ln -s /Applications Applications
cd ../
contrib/dmgbuild/custom_dsstore.py "dist/.DS_Store" "PirateCash-Qt"
genisoimage -no-cache-inodes -D -l -probe -V "PirateCash-Qt" -no-pad -r -dir-mode 0755 -apple -o PirateCash-Qt-uncompressed.dmg dist
dmg dmg PirateCash-Qt-uncompressed.dmg PirateCash-Qt.dmg
rm PirateCash-Qt-uncompressed.dmg dpi36.background.tiff dpi72.background.tiff
