#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
//   0x63ecd7e,
//   0xc61b61ac,
//   0xc632f359,
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
