description "Cosanta Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env COSANTAD_BIN="/usr/bin/cosantad"
env COSANTAD_USER="cosantacore"
env COSANTAD_GROUP="cosantacore"
env COSANTAD_PIDDIR="/var/run/cosantad"
# upstart can't handle variables constructed with other variables
env COSANTAD_PIDFILE="/var/run/cosantad/cosantad.pid"
env COSANTAD_CONFIGFILE="/etc/cosantacore/cosanta.conf"
env COSANTAD_DATADIR="/var/lib/cosantad"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # cosantad will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$COSANTAD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run cosantad."
        echo "The setting must appear in $COSANTAD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Cosanta Core Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$COSANTAD_PIDDIR"
    chmod 0755 "$COSANTAD_PIDDIR"
    chown $COSANTAD_USER:$COSANTAD_GROUP "$COSANTAD_PIDDIR"
    chown $COSANTAD_USER:$COSANTAD_GROUP "$COSANTAD_CONFIGFILE"
    chmod 0660 "$COSANTAD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$COSANTAD_PIDFILE" \
    --chuid $COSANTAD_USER:$COSANTAD_GROUP \
    --exec "$COSANTAD_BIN" \
    -- \
    -pid="$COSANTAD_PIDFILE" \
    -conf="$COSANTAD_CONFIGFILE" \
    -datadir="$COSANTAD_DATADIR" \
    -disablewallet \
    -daemon

