services:
  container:
    entrypoint: /bin/bash
    build:
      context: '..'
      dockerfile: './develop/Dockerfile'
      args:
        USER_ID: 1000   # set this to $(id -u) of the host
        GROUP_ID: 1000  # set this to $(id -g) of the host
    ports:
      - "19606:19606"         # Mainnet Ports
      - "63636:63636"
      - "19696:19696"         # Testnet Ports
      - "50666:50666"
    security_opt:
      - seccomp:unconfined
    stdin_open: true  # Equivalent to -i
    tty: true         # Equivalent to -t
    volumes:
      - type: bind
        source: ../../..
        target: /piratecash-src
